### ISSUE TITLE
Could you please give some refs?

### ISSUE THREAD

**Issue by zhangjun-xyz** [apennisi/jpdaf_tracking#1]
I am interested in your project. There are many formulas in your code and I wonder whether you can give some references on it?

**Comment by apennisi** [comment]
Hi,
I followed more or less the following paper:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.158.2694&rep=rep1&type=pdf
Check it out!
Andrea

**Comment by zhanghm1995** [comment]
Hi, @apennisi @zhangjun-xyz
Could you offer the paper title you refered to in this code? I cannot open the link you offered above.

Thanks in advance!

**Comment by wangx1996** [comment]
> Hi, @apennisi @zhangjun-xyz
> Could you offer the paper title you refered to in this code? I cannot open the link you offered above.
> 
> Thanks in advance!

师兄，你还要这篇文章吗，你这是今年的评论吧

**Comment by wangx1996** [comment]
> Hi, @apennisi @zhangjun-xyz
> Could you offer the paper title you refered to in this code? I cannot open the link you offered above.
> 
> Thanks in advance!

师兄，你还要这个论文吗？你这是今年的评论？
