### ISSUE TITLE
formula error

### ISSUE THREAD

**Issue by wangx1996** [apennisi/jpdaf_tracking#10]
Hello, I read your code and the paper about JPDAF, and I found there has a different about the covariance update between  the code and  paper
The code is in the kalman.cpp
`
114    Pk = Pk + beta(i) * (a * a.transpose() - x_filter * x_filter.transpose());
`
I compare this formula with the paper, and I think the brackets should not at the end of this formula, I consider this formula should be like this:
    Pk = Pk + beta(i) * (a * a.transpose()) - x_filter * x_filter.transpose();
In this way, the final formula is consistent with the paper.

**Comment by apennisi** [comment]
Hey @wangx1996 , during the Christmas holidays, I am going to review the code! Thanks for the notification

**Comment by LC041336** [comment]
@wangx1996 Hi bro, apennisi is right. Maybe you can refer to this formula image which i do the screen shot from the net.The first line result in image is from P matrix in gainUpdate function. The second line result is from Pk. Then  the final result is line of code 118 "P+=Pk" 
![formula](https://user-images.githubusercontent.com/35520068/102762175-dfa05b00-43b2-11eb-93bd-83401cdb2bbf.png)

**Comment by wangx1996** [comment]
> @wangx1996 Hi bro, apennisi is right. Maybe you can refer to this formula image which i do the screen shot from the net.The first line result in image is from P matrix in gainUpdate function. The second line result is from Pk. Then the final result is line of code 118 "P+=Pk"
> ![图片](https://user-images.githubusercontent.com/35520068/102762091-c0093280-43b2-11eb-80e9-574e86bcf7ee.png)

Thanks for your reply. Would you please give me the link about this formula?

**Comment by wangx1996** [comment]
@LC041336 Thanks for your reply. Would you please give me the link about this formula?

**Comment by LC041336** [comment]
Reference Link : http://www.doc88.com/p-9768233601246.html. You can focus on the page 27 (Pt(k|k)=..........)

**Comment by wangx1996** [comment]
@LC041336  Thanks a lot，and this formula is the same as the apennisi. But I derive this formula again, I found it is  a little bit different about the paper. The Pk in paper is like this:
![f2](https://user-images.githubusercontent.com/32057102/102766842-b636fd80-43b9-11eb-8ff3-60b16b4379f6.png)
And I derive the formula in the slides which is the same as apennisi, I cannot obtain the formula in the paper. Is there something wrong about the process that I derive?
![IMG_20201221_181952_edit_855027035441407(1)](https://user-images.githubusercontent.com/32057102/102767144-175ed100-43ba-11eb-836a-23de05bf08ff.jpg)

![IMG_20201221_182006](https://user-images.githubusercontent.com/32057102/102767163-1d54b200-43ba-11eb-94dd-046ebecf27bd.jpg)

**Comment by chisyliu** [comment]
Hi  @wangx1996
The equation is correct, please see (42, 43, 44) in paper: The probabilistic data association filter, IEEE CONTROL SYSTEMS MAGAZINE, 2009.
