### ISSUE TITLE
the result is actually bad

### ISSUE THREAD

**Issue by jeannotes** [apennisi/jpdaf_tracking#3]
hi, I've run your code, but I find that many times it has not associate with previous time. Did you notice that

**Comment by apennisi** [comment]
Are you testing the code on your dataset? did you make your own config file?

**Comment by jeannotes** [comment]
@apennisi I use your config files and images, ground truth is beautiful, but associations' result is bad

**Comment by apennisi** [comment]
Can you be more precise?

**Comment by jeannotes** [comment]
@apennisi 

for one frame, we should see that it should be assigned (10),(13),(11) , but in this algorithm it is still (1,3,2,0,4) etc

for multi frame, the way we judge an association problem is to see that if this frame's matching number is equal to next frame's matching number
but I see that many times, they are not equally.

I didn't read your code clearly, hope you to answer them, thanks .

the image cannot be uploaded due to my network, I have send a mail to you.

**Comment by apennisi** [comment]
I think you are confusing the meaning of the ground truth...that ground truth is referred to "detections"  and not "tracks".

**Comment by jeannotes** [comment]
@apennisi but why the matching number in the left part of the whole pictue is changing.

**Comment by jeannotes** [comment]
![Screenshot from 2019-05-21 17-48-16](https://user-images.githubusercontent.com/13599324/58088169-a90dc780-7bf4-11e9-9187-a02e047bd491.png)

**Comment by apennisi** [comment]
Because, those are the detections and I read them in the same order written in the "detections.txt" file.
