### ISSUE TITLE
Getting too many errors on compilation

### ISSUE THREAD

**Issue by controlsgeek** [apennisi/jpdaf_tracking#4]
Hi! 
I tried to compile to code with the instructions given, but it gave too many errors. 
I tried correcting few errors, but more and more keep coming.

I have added the logs.
Any help shall be usefull. 

Thanks

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /opt/ros/kinetic (found version "3.3.1") 
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sagar/Downloads/jpdaf_tracking-master/build
sagar@sagar-HP-Pavilion-Notebook:~/Downloads/jpdaf_tracking-master/build$ make -j5
Scanning dependencies of target jpdaf_tracker
[ 10%] Building CXX object CMakeFiles/jpdaf_tracker.dir/src/tracker.cpp.o
[ 20%] Building CXX object CMakeFiles/jpdaf_tracker.dir/src/imagemanager.cpp.o
[ 40%] Building CXX object CMakeFiles/jpdaf_tracker.dir/src/main.cpp.o
[ 40%] Building CXX object CMakeFiles/jpdaf_tracker.dir/src/track.cpp.o
[ 50%] Building CXX object CMakeFiles/jpdaf_tracker.dir/src/local_tracker.cpp.o
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:38:6: error: #elif with no expression
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:65:6: error: #elif with no expression
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:31:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:54:36: error: ‘string’ in namespace ‘std’ does not name a type
   explicit ImageManager(const std::string& dir);
                                    ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:62:8: error: ‘string’ in namespace ‘std’ does not name a type
   std::string getNext(const int& speed);
        ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:70:28: error: ‘string’ is not a member of ‘std’
   void sorting(std::vector<std::string>& data) const;
                            ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:70:28: error: ‘string’ is not a member of ‘std’
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:70:39: error: template argument 1 is invalid
   void sorting(std::vector<std::string>& data) const;
                                       ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:70:39: error: template argument 2 is invalid
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:71:15: error: ‘string’ is not a member of ‘std’
   std::vector<std::string> getAllFilesInFolder(const std::string& path) const;
               ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:71:15: error: ‘string’ is not a member of ‘std’
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:71:26: error: template argument 1 is invalid
   std::vector<std::string> getAllFilesInFolder(const std::string& path) const;
                          ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:71:26: error: template argument 2 is invalid
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:71:59: error: ‘string’ in namespace ‘std’ does not name a type
   std::vector<std::string> getAllFilesInFolder(const std::string& path) const;
                                                           ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:72:3: error: ‘size_t’ does not name a type
   size_t currentFrameIndex;
   ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:73:15: error: ‘string’ is not a member of ‘std’
   std::vector<std::string> fileNames;
               ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:73:15: error: ‘string’ is not a member of ‘std’
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:73:26: error: template argument 1 is invalid
   std::vector<std::string> fileNames;
                          ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:73:26: error: template argument 2 is invalid
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:32:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/natural_less.h: In function ‘int strcmp_natural(const char*, const char*)’:
/home/sagar/Downloads/jpdaf_tracking-master/src/natural_less.h:36:34: error: ‘numeric_limits’ is not a member of ‘std’
         if (lengthA - lengthB >= std::numeric_limits<int>::max())
                                  ^
/home/sagar/Downloads/jpdaf_tracking-master/src/natural_less.h:36:54: error: expected primary-expression before ‘int’
         if (lengthA - lengthB >= std::numeric_limits<int>::max())
                                                      ^
/home/sagar/Downloads/jpdaf_tracking-master/src/natural_less.h:36:54: error: expected ‘)’ before ‘int’
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp: At global scope:
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:43:26: error: prototype for ‘std::vector<std::__cxx11::basic_string<char> > ImageManager::getAllFilesInFolder(const string&) const’ does not match any in class ‘ImageManager’
 std::vector<std::string> ImageManager::getAllFilesInFolder(const std::string& path) const
                          ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:31:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:71:28: error: candidate is: int ImageManager::getAllFilesInFolder(const int&) const
   std::vector<std::string> getAllFilesInFolder(const std::string& path) const;
                            ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:85:1: error: prototype for ‘ImageManager::ImageManager(const string&)’ does not match any in class ‘ImageManager’
 ImageManager::ImageManager(const std::string& dir)
 ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:31:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:45:7: error: candidates are: constexpr ImageManager::ImageManager(ImageManager&&)
 class ImageManager
       ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:45:7: error:                 constexpr ImageManager::ImageManager(const ImageManager&)
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:54:12: error:                 ImageManager::ImageManager(const int&)
   explicit ImageManager(const std::string& dir);
            ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:94:6: error: prototype for ‘void ImageManager::sorting(std::vector<std::__cxx11::basic_string<char> >&) const’ does not match any in class ‘ImageManager’
 void ImageManager::sorting(std::vector<std::string>& data) const
      ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:31:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.h:70:8: error: candidate is: void ImageManager::sorting(int&) const
   void sorting(std::vector<std::string>& data) const;
        ^
/home/sagar/Downloads/jpdaf_tracking-master/src/imagemanager.cpp:99:51: error: no ‘std::__cxx11::string ImageManager::getNext(const int&)’ member function declared in class ‘ImageManager’
 std::string ImageManager::getNext(const int& speed)
                                                   ^
CMakeFiles/jpdaf_tracker.dir/build.make:86: recipe for target 'CMakeFiles/jpdaf_tracker.dir/src/imagemanager.cpp.o' failed
make[2]: *** [CMakeFiles/jpdaf_tracker.dir/src/imagemanager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/track.cpp:1:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const cv::Mat& JPDAFTracker::Track::S_cv() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:93:15: warning: reference to local variable ‘Scv’ returned [-Wreturn-local-addr]
       cv::Mat Scv;
               ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/track.cpp:1:0:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const Vector4f& JPDAFTracker::Track::getUpdate() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:154:28: warning: returning reference to temporary [-Wreturn-local-addr]
       return KF->getUpdate();
                            ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34:0,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/main.cpp:2:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const cv::Mat& JPDAFTracker::Track::S_cv() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:93:15: warning: reference to local variable ‘Scv’ returned [-Wreturn-local-addr]
       cv::Mat Scv;
               ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34:0,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/main.cpp:2:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const Vector4f& JPDAFTracker::Track::getUpdate() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:154:28: warning: returning reference to temporary [-Wreturn-local-addr]
       return KF->getUpdate();
                            ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34:0,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.cpp:1:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const cv::Mat& JPDAFTracker::Track::S_cv() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:93:15: warning: reference to local variable ‘Scv’ returned [-Wreturn-local-addr]
       cv::Mat Scv;
               ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34:0,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.cpp:1:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const Vector4f& JPDAFTracker::Track::getUpdate() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:154:28: warning: returning reference to temporary [-Wreturn-local-addr]
       return KF->getUpdate();
                            ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34:0,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.h:4,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:1:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const cv::Mat& JPDAFTracker::Track::S_cv() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:93:15: warning: reference to local variable ‘Scv’ returned [-Wreturn-local-addr]
       cv::Mat Scv;
               ^
In file included from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34:0,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.h:4,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:1:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h: In member function ‘const Vector4f& JPDAFTracker::Track::getUpdate() const’:
/home/sagar/Downloads/jpdaf_tracking-master/src/track.h:154:28: warning: returning reference to temporary [-Wreturn-local-addr]
       return KF->getUpdate();
                            ^
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp: In member function ‘virtual void JPDAFTracker::LocalTracker::delete_tracks()’:
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:90:10: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
       [](auto& currentTrack) { return !currentTrack->isAlive() && currentTrack->getId() != -1; }),
          ^
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp: In lambda function:
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:90:52: error: base operand of ‘->’ is not a pointer
       [](auto& currentTrack) { return !currentTrack->isAlive() && currentTrack->getId() != -1; }),
                                                    ^
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:90:79: error: base operand of ‘->’ is not a pointer
       [](auto& currentTrack) { return !currentTrack->isAlive() && currentTrack->getId() != -1; }),
                                                                               ^
In file included from /usr/include/c++/5/bits/stl_algobase.h:71:0,
                 from /usr/include/c++/5/memory:62,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/track.h:34,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/tracker.h:34,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.h:4,
                 from /home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:1:
/usr/include/c++/5/bits/predefined_ops.h: In instantiation of ‘bool __gnu_cxx::__ops::_Iter_pred<_Predicate>::operator()(_Iterator) [with _Iterator = __gnu_cxx::__normal_iterator<std::shared_ptr<JPDAFTracker::Track>*, std::vector<std::shared_ptr<JPDAFTracker::Track> > >; _Predicate = JPDAFTracker::LocalTracker::delete_tracks()::<lambda(int&)>]’:
/usr/include/c++/5/bits/stl_algo.h:866:20:   required from ‘_ForwardIterator std::__remove_if(_ForwardIterator, _ForwardIterator, _Predicate) [with _ForwardIterator = __gnu_cxx::__normal_iterator<std::shared_ptr<JPDAFTracker::Track>*, std::vector<std::shared_ptr<JPDAFTracker::Track> > >; _Predicate = __gnu_cxx::__ops::_Iter_pred<JPDAFTracker::LocalTracker::delete_tracks()::<lambda(int&)> >]’
/usr/include/c++/5/bits/stl_algo.h:936:30:   required from ‘_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = __gnu_cxx::__normal_iterator<std::shared_ptr<JPDAFTracker::Track>*, std::vector<std::shared_ptr<JPDAFTracker::Track> > >; _Predicate = JPDAFTracker::LocalTracker::delete_tracks()::<lambda(int&)>]’
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:90:97:   required from here
/usr/include/c++/5/bits/predefined_ops.h:234:30: error: no match for call to ‘(JPDAFTracker::LocalTracker::delete_tracks()::<lambda(int&)>) (std::shared_ptr<JPDAFTracker::Track>&)’
  { return bool(_M_pred(*__it)); }
                              ^
/usr/include/c++/5/bits/predefined_ops.h:234:30: note: candidate: void (*)(int&) <conversion>
/usr/include/c++/5/bits/predefined_ops.h:234:30: note:   candidate expects 2 arguments, 2 provided
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:90:28: note: candidate: JPDAFTracker::LocalTracker::delete_tracks()::<lambda(int&)>
       [](auto& currentTrack) { return !currentTrack->isAlive() && currentTrack->getId() != -1; }),
                            ^
/home/sagar/Downloads/jpdaf_tracking-master/src/local_tracker.cpp:90:28: note:   no known conversion for argument 1 from ‘std::shared_ptr<JPDAFTracker::Track>’ to ‘int&’
CMakeFiles/jpdaf_tracker.dir/build.make:158: recipe for target 'CMakeFiles/jpdaf_tracker.dir/src/local_tracker.cpp.o' failed
make[2]: *** [CMakeFiles/jpdaf_tracker.dir/src/local_tracker.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jpdaf_tracker.dir/all' failed
make[1]: *** [CMakeFiles/jpdaf_tracker.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by apennisi** [comment]
Try to comment from line 45 to 65 of the file imagemanager.cpp as well as the line 82.
Let me know.

**Comment by apennisi** [comment]
I apologies for your problems, unfortunately, many months ago I accepted a commit without verifying it. And it made a mess. Now, I reverted to my original version and it works well. So, check it out!

**Comment by controlsgeek** [comment]
Works like a charm! Thanks!

**Comment by controlsgeek** [comment]
Hi @apennisi !
I have been trying to understand the code, and I get the idea of generating association, hypothesis, calculating joint probability and filter update for all the tracks which takes place in local tracker.

I don't exactly understand what happens in the global tracker. The global tracker also has association, hypothesis generation, joint probability and filter update. Can you please briefly explain the difference between global and local tracker? I read the reference you had mentioned in an issue but it did not mention local and global tracker.  

Thanks!

Edit:
From what I understood:
1) Whenever a new not_associated detection is found, it is tried to match with previous detection using eucledian distance and Hungarian Algo. All such tracks at a particular time are pushed as local_tracks.

2) JPDAF takes place at local level for all the tracks

3) In Global_Tracker, it takes all the tracks from local_tracker which were successfully associated and applies JPDAF again which would be the final result? 

Am I thinking in the right direction? What would be the advantage of this process? It avoids huge association matrices and hence hypothesis generation? And leads to increase in speed?
