### ISSUE TITLE
Frame rate drops as time passes

### ISSUE THREAD

**Issue by ghost** [apennisi/jpdaf_tracking#6]
Hello,

as I stated in the title, tracker gets slower (computation time increases),while time passes. As time passes, there is increase of number of hypothesis although number of detection does not change as much. For more dense detections in my own datasets, I can observe the performance degradation rapidly. I tried to figure out the root problem but I am not able to succeed up to now. Let me share my debug prints for PETS09 datasets. In short, "Average time in second per track iteration is:" value increases.

**************
****PARAMS****
**************
[PD]: 1
[PG]: 0.4
[LOCAL_GSIGMA]: 15
[GLOBAL_GSIGMA]: 0.1
[LAMBDA]: 2
[GAMMA]: 2e-06
[R_MATRIX]; 100   0
  0 100
[TARGET_DELTA]: 10, 10
[DT]: 0.4
[LOCAL_ASSOCIATION_COST]: 40
[GLOBAL_ASSOCIATION_COST]: 50
**************
#########################################################
image number: 0
num of detections: 3
init_ state ended: 
Average time in second per track iteration is: 1.1164e-05
Average time in second per draw tracks iteration is: 0.206693
#########################################################
image number: 1
num of detections: 3
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 3
--------manage_new_tracks() deteSize: 3
--------manage_new_tracks()2---------
--------manage_new_tracks()3---------
manage_new_tracks() assignmentBin.rows: 3
manage_new_tracks() assignmentBin.cols: 3
manage_new_tracks() tracker->size(): 3
# Average time in second per track iteration is: 0.000163129
Average time in second per draw tracks iteration is: 0.176309
#########################################################
image number: 2
num of detections: 5
localTrackers_.size(): 1
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
Generate hypothesis q rows: 4
Generate hypothesis q cols: 4
hyp_num: 10
Tracks Size Before Compute Volume: 3
All the detections are not associated: 0.00699479
Track Size Before Global Association Start: 3
Detection Size: 5
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 7.1266e-05
q.total is less than or equal to zero: 
Accumulated Time: 0.00706606
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 0
--------manage_new_tracks() deteSize: 1
# Average time in second per track iteration is: 0.0024822
Average time in second per draw tracks iteration is: 0.166269
#########################################################
image number: 3
num of detections: 3
localTrackers_.size(): 1
Generate hypothesis q rows: 3
Generate hypothesis q cols: 4
hyp_num: 7
Tracks Size Before Compute Volume: 3
All the detections are not associated: 0.00567358
Track Size Before Global Association Start: 3
Detection Size: 3
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 3.1594e-05
q.total is less than or equal to zero: 
Accumulated Time: 0.00570517
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 1
--------manage_new_tracks() deteSize: 0
# Average time in second per track iteration is: 0.00329848
Average time in second per draw tracks iteration is: 0.160863
#########################################################
image number: 4
num of detections: 4
localTrackers_.size(): 1
Generate hypothesis q rows: 3
Generate hypothesis q cols: 4
hyp_num: 7
Tracks Size Before Compute Volume: 3
All the detections are not associated: 0.004824
Track Size Before Global Association Start: 3
Detection Size: 4
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 3.9157e-05
q.total is less than or equal to zero: 
Accumulated Time: 0.00486316
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 0
--------manage_new_tracks() deteSize: 1
num Average time in second per track iteration is: 0.00361939
Average time in second per draw tracks iteration is: 0.15761
#########################################################
image number: 5
num of detections: 4
localTrackers_.size(): 1
Generate hypothesis q rows: 4
Generate hypothesis q cols: 4
hyp_num: 10
Tracks Size Before Compute Volume: 3
All the detections are not associated: 0.00475154
Track Size Before Global Association Start: 3
Detection Size: 4
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 5.9171e-05
q.total is less than or equal to zero: 
Accumulated Time: 0.00481071
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 1
--------manage_new_tracks() deteSize: 0
# Average time in second per track iteration is: 0.00382761
Average time in second per draw tracks iteration is: 0.155388
#########################################################
image number: 6
num of detections: 4
localTrackers_.size(): 1
Generate hypothesis q rows: 4
Generate hypothesis q cols: 4
hyp_num: 10
Tracks Size Before Compute Volume: 3
All the detections are not associated: 0.00526759
Track Size Before Global Association Start: 3
Detection Size: 4
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 3.8898e-05
q.total is less than or equal to zero: 
Accumulated Time: 0.00530649
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 0
--------manage_new_tracks() deteSize: 0
# Average time in second per track iteration is: 0.00404474
Average time in second per draw tracks iteration is: 0.154009
#########################################################
image number: 104
num of detections: 5
localTrackers_.size(): 4
entropy_sentinel: ACCEPT, life_time: 107
entropy_sentinel: ACCEPT, life_time: 105
entropy_sentinel: ACCEPT, life_time: 127
Generate hypothesis q rows: 3
Generate hypothesis q cols: 4
hyp_num: 9
Tracks Size Before Compute Volume: 3
entropy_sentinel: ACCEPT, life_time: 93
Generate hypothesis q rows: 2
Generate hypothesis q cols: 2
hyp_num: 3
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 69
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
All the detections are not associated: 0.0138701
Track Size Before Global Association Start: 6
Detection Size: 5
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 8.6709e-05
q.total is less than or equal to zero: 
Accumulated Time: 0.0139568
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 0
--------manage_new_tracks() deteSize: 0
# Average time in second per track iteration is: 0.0115828
Average time in second per draw tracks iteration is: 0.144938
#########################################################
image number: 793
num of detections: 7
localTrackers_.size(): 24
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
entropy_sentinel: ACCEPT, life_time: 511
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 357
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 294
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: DISCARD, nodetections: 279
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
entropy_sentinel: ACCEPT, life_time: 267
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
life_time == 0, initial_entropy: 6.062
life_time == 0, initial_entropy: 6.062
entropy_sentinel: ACCEPT, life_time: 213
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 250
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: DISCARD, nodetections: 135
entropy_sentinel: DISCARD, nodetections: 185
entropy_sentinel: ACCEPT, life_time: 187
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 113
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 165
Generate hypothesis q rows: 1
Generate hypothesis q cols: 2
hyp_num: 2
Tracks Size Before Compute Volume: 1
entropy_sentinel: ACCEPT, life_time: 105
Generate hypothesis q rows: 2
Generate hypothesis q cols: 2
hyp_num: 3
Tracks Size Before Compute Volume: 1
life_time == 0, initial_entropy: 6.062
entropy_sentinel: ACCEPT, life_time: 54
Generate hypothesis q rows: 2
Generate hypothesis q cols: 2
hyp_num: 3
Tracks Size Before Compute Volume: 1
life_time == 0, initial_entropy: 6.062
All the detections are not associated: 0.0372968
Track Size Before Global Association Start: 24
Detection Size: 7
GLOBAL ASSOCIATION STARTED: 
ASSOCIATION ENDED: 0.000416706
ASSIGN ALL THE NOT ASSOCIATED TRACKS STARTED: 
ASSIGN ALL THE NOT ASSOCIATED TRACKS ENDED: 2.106e-05
GENERATE HYPOTHESIS STARTED: 
Generate hypothesis q rows: 1
Generate hypothesis q cols: 25
GENERATE HYPOTHESIS ENDED: 0.00309006
COMPUTE JOINT PROBABILITY STARTED
hyp_num: 4
Tracks Size Before Compute Volume: 24
COMPUTE JOINT PROBABILITY ENDED: 0.0001155
KALMAN PREDICT STEP STARTED: 
KALMAN PREDICT STEP ENDED: 3.379e-05
UPDATE AND CORRECT STARTED: 
UPDATE AND CORRECT ENDED: 4.9075e-05
Accumulated Time: 0.041023
--------manage_new_tracks()1---------
--------manage_new_tracks() prevDetSize: 0
--------manage_new_tracks() deteSize: 0
# Average time in second per track iteration is: 0.0248247
Average time in second per draw tracks iteration is: 0.144375

**Comment by apennisi** [comment]
hey @capricornfati , during this Christmas Holidays, I am going to review the code!
