### ISSUE TITLE
useless const idx???

### ISSUE THREAD

**Issue by LC041336** [apennisi/jpdaf_tracking#8]
Maybe 'prev_detections_.push_back(not_associated_.at(idx));'

https://github.com/apennisi/jpdaf_tracking/blob/7f2783ae163e9e6553a2e11a1bd6ff2cea5569ea/src/global_tracker.cpp#L225

**Comment by apennisi** [comment]
Hey @LC041336 , during the Christmas holidays, I am going to review the code and I will let you know.

**Comment by apennisi** [comment]
Fixed (with 3 years of delay)
