### ISSUE TITLE
The process of the associate algorithm?

### ISSUE THREAD

**Issue by wangx1996** [apennisi/jpdaf_tracking#9]
Hello, I read your code and got one question: why there has two times associate in the code? first time is the local tracker, second time is the global tracker.

**Comment by LC041336** [comment]
@wangx1996 Some necessary and key info for you:
1. "typedef std::vector<LocalTracker_ptr> LocalTrackers;" in global tracker.hpp
2. threshold in local / group association is different, refer to the config/params.txt 
3. search the localTrackers_ in global_tracker.cpp to see the rough  localTrackers_ data flow

My Guess:
1.local_tracker class is used for the current frame associate with detection
2.global tracker class is used for the association from start frame to current frame(including multi-frame local tracker data) with detection
